// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _hokuyo_data_scan_h
#define _hokuyo_data_scan_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _hokuyo_data_scan hokuyo_data_scan;
struct _hokuyo_data_scan
{
    float      timestamp;
    float      angle_min;
    float      angle_max;
    float      angle_increment;
    float      time_increment;
    float      scan_time;
    float      range_min;
    float      range_max;
    int32_t    ranges_length;
    float      *ranges;
    int32_t    intensities_length;
    float      *intensities;
};

/**
 * Create a deep copy of a hokuyo_data_scan.
 * When no longer needed, destroy it with hokuyo_data_scan_destroy()
 */
hokuyo_data_scan* hokuyo_data_scan_copy(const hokuyo_data_scan* to_copy);

/**
 * Destroy an instance of hokuyo_data_scan created by hokuyo_data_scan_copy()
 */
void hokuyo_data_scan_destroy(hokuyo_data_scan* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _hokuyo_data_scan_subscription_t hokuyo_data_scan_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * hokuyo_data_scan is received.
 */
typedef void(*hokuyo_data_scan_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const hokuyo_data_scan *msg, void *userdata);

/**
 * Publish a message of type hokuyo_data_scan using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int hokuyo_data_scan_publish(lcm_t *lcm, const char *channel, const hokuyo_data_scan *msg);

/**
 * Subscribe to messages of type hokuyo_data_scan using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is received.
 *                This function is invoked by LCM during calls to lcm_handle() and
 *                lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
hokuyo_data_scan_subscription_t* hokuyo_data_scan_subscribe(lcm_t *lcm, const char *channel, hokuyo_data_scan_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by hokuyo_data_scan_subscribe()
 */
int hokuyo_data_scan_unsubscribe(lcm_t *lcm, hokuyo_data_scan_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int hokuyo_data_scan_subscription_set_queue_capacity(hokuyo_data_scan_subscription_t* subs,
                              int num_messages);

/**
 * Encode a message of type hokuyo_data_scan into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to hokuyo_data_scan_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int hokuyo_data_scan_encode(void *buf, int offset, int maxlen, const hokuyo_data_scan *p);

/**
 * Decode a message of type hokuyo_data_scan from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with hokuyo_data_scan_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int hokuyo_data_scan_decode(const void *buf, int offset, int maxlen, hokuyo_data_scan *msg);

/**
 * Release resources allocated by hokuyo_data_scan_decode()
 * @return 0
 */
int hokuyo_data_scan_decode_cleanup(hokuyo_data_scan *p);

/**
 * Check how many bytes are required to encode a message of type hokuyo_data_scan
 */
int hokuyo_data_scan_encoded_size(const hokuyo_data_scan *p);

// LCM support functions. Users should not call these
int64_t __hokuyo_data_scan_get_hash(void);
uint64_t __hokuyo_data_scan_hash_recursive(const __lcm_hash_ptr *p);
int     __hokuyo_data_scan_encode_array(void *buf, int offset, int maxlen, const hokuyo_data_scan *p, int elements);
int     __hokuyo_data_scan_decode_array(const void *buf, int offset, int maxlen, hokuyo_data_scan *p, int elements);
int     __hokuyo_data_scan_decode_array_cleanup(hokuyo_data_scan *p, int elements);
int     __hokuyo_data_scan_encoded_array_size(const hokuyo_data_scan *p, int elements);
int     __hokuyo_data_scan_clone_array(const hokuyo_data_scan *p, hokuyo_data_scan *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
