// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "lcmtypes/hokuyo_data_scan.h"

static int __hokuyo_data_scan_hash_computed;
static uint64_t __hokuyo_data_scan_hash;

uint64_t __hokuyo_data_scan_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __hokuyo_data_scan_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__hokuyo_data_scan_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x477ed32a79e3af3fLL
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __hokuyo_data_scan_get_hash(void)
{
    if (!__hokuyo_data_scan_hash_computed) {
        __hokuyo_data_scan_hash = (int64_t)__hokuyo_data_scan_hash_recursive(NULL);
        __hokuyo_data_scan_hash_computed = 1;
    }

    return __hokuyo_data_scan_hash;
}

int __hokuyo_data_scan_encode_array(void *buf, int offset, int maxlen, const hokuyo_data_scan *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].angle_min), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].angle_max), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].angle_increment), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].time_increment), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].scan_time), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].range_min), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].range_max), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ranges_length), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].ranges, p[element].ranges_length);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].intensities_length), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].intensities, p[element].intensities_length);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int hokuyo_data_scan_encode(void *buf, int offset, int maxlen, const hokuyo_data_scan *p)
{
    int pos = 0, thislen;
    int64_t hash = __hokuyo_data_scan_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __hokuyo_data_scan_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __hokuyo_data_scan_encoded_array_size(const hokuyo_data_scan *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __float_encoded_array_size(&(p[element].timestamp), 1);

        size += __float_encoded_array_size(&(p[element].angle_min), 1);

        size += __float_encoded_array_size(&(p[element].angle_max), 1);

        size += __float_encoded_array_size(&(p[element].angle_increment), 1);

        size += __float_encoded_array_size(&(p[element].time_increment), 1);

        size += __float_encoded_array_size(&(p[element].scan_time), 1);

        size += __float_encoded_array_size(&(p[element].range_min), 1);

        size += __float_encoded_array_size(&(p[element].range_max), 1);

        size += __int32_t_encoded_array_size(&(p[element].ranges_length), 1);

        size += __float_encoded_array_size(p[element].ranges, p[element].ranges_length);

        size += __int32_t_encoded_array_size(&(p[element].intensities_length), 1);

        size += __float_encoded_array_size(p[element].intensities, p[element].intensities_length);

    }
    return size;
}

int hokuyo_data_scan_encoded_size(const hokuyo_data_scan *p)
{
    return 8 + __hokuyo_data_scan_encoded_array_size(p, 1);
}

int __hokuyo_data_scan_decode_array(const void *buf, int offset, int maxlen, hokuyo_data_scan *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].angle_min), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].angle_max), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].angle_increment), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].time_increment), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].scan_time), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].range_min), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].range_max), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ranges_length), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].ranges = (float*) lcm_malloc(sizeof(float) * p[element].ranges_length);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].ranges, p[element].ranges_length);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].intensities_length), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].intensities = (float*) lcm_malloc(sizeof(float) * p[element].intensities_length);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].intensities, p[element].intensities_length);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __hokuyo_data_scan_decode_array_cleanup(hokuyo_data_scan *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_decode_array_cleanup(&(p[element].timestamp), 1);

        __float_decode_array_cleanup(&(p[element].angle_min), 1);

        __float_decode_array_cleanup(&(p[element].angle_max), 1);

        __float_decode_array_cleanup(&(p[element].angle_increment), 1);

        __float_decode_array_cleanup(&(p[element].time_increment), 1);

        __float_decode_array_cleanup(&(p[element].scan_time), 1);

        __float_decode_array_cleanup(&(p[element].range_min), 1);

        __float_decode_array_cleanup(&(p[element].range_max), 1);

        __int32_t_decode_array_cleanup(&(p[element].ranges_length), 1);

        __float_decode_array_cleanup(p[element].ranges, p[element].ranges_length);
        if (p[element].ranges) free(p[element].ranges);

        __int32_t_decode_array_cleanup(&(p[element].intensities_length), 1);

        __float_decode_array_cleanup(p[element].intensities, p[element].intensities_length);
        if (p[element].intensities) free(p[element].intensities);

    }
    return 0;
}

int hokuyo_data_scan_decode(const void *buf, int offset, int maxlen, hokuyo_data_scan *p)
{
    int pos = 0, thislen;
    int64_t hash = __hokuyo_data_scan_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __hokuyo_data_scan_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int hokuyo_data_scan_decode_cleanup(hokuyo_data_scan *p)
{
    return __hokuyo_data_scan_decode_array_cleanup(p, 1);
}

int __hokuyo_data_scan_clone_array(const hokuyo_data_scan *p, hokuyo_data_scan *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __float_clone_array(&(p[element].angle_min), &(q[element].angle_min), 1);

        __float_clone_array(&(p[element].angle_max), &(q[element].angle_max), 1);

        __float_clone_array(&(p[element].angle_increment), &(q[element].angle_increment), 1);

        __float_clone_array(&(p[element].time_increment), &(q[element].time_increment), 1);

        __float_clone_array(&(p[element].scan_time), &(q[element].scan_time), 1);

        __float_clone_array(&(p[element].range_min), &(q[element].range_min), 1);

        __float_clone_array(&(p[element].range_max), &(q[element].range_max), 1);

        __int32_t_clone_array(&(p[element].ranges_length), &(q[element].ranges_length), 1);

        q[element].ranges = (float*) lcm_malloc(sizeof(float) * q[element].ranges_length);
        __float_clone_array(p[element].ranges, q[element].ranges, p[element].ranges_length);

        __int32_t_clone_array(&(p[element].intensities_length), &(q[element].intensities_length), 1);

        q[element].intensities = (float*) lcm_malloc(sizeof(float) * q[element].intensities_length);
        __float_clone_array(p[element].intensities, q[element].intensities, p[element].intensities_length);

    }
    return 0;
}

hokuyo_data_scan *hokuyo_data_scan_copy(const hokuyo_data_scan *p)
{
    hokuyo_data_scan *q = (hokuyo_data_scan*) malloc(sizeof(hokuyo_data_scan));
    __hokuyo_data_scan_clone_array(p, q, 1);
    return q;
}

void hokuyo_data_scan_destroy(hokuyo_data_scan *p)
{
    __hokuyo_data_scan_decode_array_cleanup(p, 1);
    free(p);
}

int hokuyo_data_scan_publish(lcm_t *lc, const char *channel, const hokuyo_data_scan *p)
{
      int max_data_size = hokuyo_data_scan_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = hokuyo_data_scan_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _hokuyo_data_scan_subscription_t {
    hokuyo_data_scan_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void hokuyo_data_scan_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    hokuyo_data_scan p;
    memset(&p, 0, sizeof(hokuyo_data_scan));
    status = hokuyo_data_scan_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding hokuyo_data_scan!!!\n", status);
        return;
    }

    hokuyo_data_scan_subscription_t *h = (hokuyo_data_scan_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    hokuyo_data_scan_decode_cleanup (&p);
}

hokuyo_data_scan_subscription_t* hokuyo_data_scan_subscribe (lcm_t *lcm,
                    const char *channel,
                    hokuyo_data_scan_handler_t f, void *userdata)
{
    hokuyo_data_scan_subscription_t *n = (hokuyo_data_scan_subscription_t*)
                       malloc(sizeof(hokuyo_data_scan_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 hokuyo_data_scan_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg hokuyo_data_scan LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int hokuyo_data_scan_subscription_set_queue_capacity (hokuyo_data_scan_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int hokuyo_data_scan_unsubscribe(lcm_t *lcm, hokuyo_data_scan_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe hokuyo_data_scan_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

